name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['8.0', '8.1', '8.2', '8.3']
        symfony: ['^6.0', '^7.0']
        exclude:
          - php: '8.0'
            symfony: '^7.0'
          - php: '8.1'
            symfony: '^7.0'

    name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }} - ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, xml, ctype, iconv
        coverage: xdebug

    - name: Validate composer.json
      run: composer validate --strict

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Symfony ${{ matrix.symfony }}
      run: |
        composer require "symfony/http-foundation:${{ matrix.symfony }}" "symfony/mime:${{ matrix.symfony }}" --no-interaction --no-update
        composer update --prefer-dist --no-interaction --no-progress

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse

    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs

    - name: Run tests
      run: XDEBUG_MODE=coverage vendor/bin/phpunit --log-junit junit.xml --coverage-clover coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: php-${{ matrix.php }}-symfony-${{ matrix.symfony }}
        name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}
        env_vars: PHP_VERSION,SYMFONY_VERSION
      env:
        PHP_VERSION: ${{ matrix.php }}
        SYMFONY_VERSION: ${{ matrix.symfony }}

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: php-${{ matrix.php }}-symfony-${{ matrix.symfony }}
        name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}
